### PR TITLE
Updated Logo design 

### PR DESCRIPTION
**Pull request by Tobaloidee**
HI @amirkhaniansev  I just edited something with the design..some alignment stuff that I fixed. Thanks!

### CODE REVIEW

**Comment by amirkhaniansev** [comment]
@Tobaloidee, please try to fix merge conflicts to enable automatic merge.

**Comment by Tobaloidee** [comment]
Im having problem when editing the Readme..please be the one to put the Logo there..thanks Sir!

**Comment by amirkhaniansev** [comment]
Just a question. Why have you edited readme?

**Comment by amirkhaniansev** [comment]
Thanks for your contribution. We really appreciate it.

**Comment by Tobaloidee** [comment]
because I just fixed the shadow there on my design...actually I removed it to be more clean..🙂 thanks again! I am interested in making a logo for AccessCore project of yours..will you permit me again?

**Comment by amirkhaniansev** [comment]
Hi @Tobaloidee. Would you like to develop icons for chat-specific operations like send, save, assign, invite, etc, so we can use them for UI in the future?

**Pull request merged**
